[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/game-server",
]
exclude = [
    "projects/game-client",
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
